FoodHouse.UI/Controllers/AutentificateController.cs
using FoodHouse.UI.Models.ViewModel.Account;
using FoodHouse.UI.Settings;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using FoodHouse.UI.Dto;

namespace FoodHouse.UI.Controllers
{
    public class AutentificateController : Controller
    {
        private readonly HttpClient httpClient;

        public AutentificateController(IHttpClientFactory httpClientFactory)
        {
            httpClient = httpClientFactory.CreateClient("APIHTTPS");
        }

        public IActionResult Register()
        {
            if (Request.Cookies["Id"] != null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(AccountRegisterViewModel viewModel)
        {
            bool number = Regex.IsMatch(viewModel.Number, RegexPatterns.PhoneNumberRegexPatten);
            bool password = Regex.IsMatch(viewModel.Password, RegexPatterns.PasswordRegexPattern);
            bool lastName = Regex.IsMatch(viewModel.LastName, RegexPatterns.NameRegexPattern);
            bool firstName = Regex.IsMatch(viewModel.FirstName, RegexPatterns.NameRegexPattern);

            viewModel.FirstNameMessage = string.Empty;
            viewModel.LastNameMessage = string.Empty;
            viewModel.NumberMessage = string.Empty;
            viewModel.EmailMessage = string.Empty;
            viewModel.PasswordMessage = string.Empty;


            string endpoint = "User/GetAll";

            var dataAboutAllUsers = await httpClient.GetFromJsonAsync<List<UserDto>>(endpoint);

            var data = dataAboutAllUsers.Where(u => u.Email == viewModel.Email);

            if (number && password && lastName && firstName && data.Count() == 0)
            {
                if (viewModel.Password == viewModel.PasswordConfirm)
                {
                    UserDto user = new UserDto()
                    {
                        Id = "",
                        Email = viewModel.Email,
                        Number = viewModel.Number,
                        Password = viewModel.Password,
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        Sex = viewModel.Sex,
                        UserType = "Client",
                        Products = new List<ProductDto>(),
                    };

                    endpoint = "User/Add";

                    var response = await httpClient.PostAsJsonAsync(endpoint, user);

                    if (response.IsSuccessStatusCode)
                    {
                        endpoint = "User/GetAll";
                        dataAboutAllUsers = await httpClient.GetFromJsonAsync<List<UserDto>>(endpoint);
                        var userData = dataAboutAllUsers.Where(u => u.Email == viewModel.Email).First();

                        CookieOptions cookie = new CookieOptions();
                        cookie.Expires = DateTime.Now.AddMinutes(60);

                        Response.Cookies.Append("Id", userData.Id, cookie);
                        Response.Cookies.Append("UserName", $"{userData.FirstName} {userData.LastName}", cookie);
                        Response.Cookies.Append("UserType", user.UserType, cookie);
                        Response.Cookies.Append("Sex", viewModel.Sex.ToString(), cookie);

                        return RedirectToAction("Index", "Home");
                    }
                }
            }

            viewModel.NumberMessage =
                RegexPatterns.AddMessage(number, "Phone number must be 10-15 digits long and start with 0");
            viewModel.PasswordMessage = RegexPatterns.AddMessage(password,
                "Password must be 8+ chars and use EN lang, include uppercase and number");
            viewModel.FirstNameMessage = RegexPatterns.AddMessage(firstName, "First Name must be 2-13 chars");
            viewModel.LastNameMessage = RegexPatterns.AddMessage(lastName, "Last Name must be 2-13 chars");
            viewModel.PasswordMessage =
                RegexPatterns.AddMessage(viewModel.Password == viewModel.PasswordConfirm, " ") == ""
                    ? viewModel.PasswordMessage
                    : "Passwords do not match";
            viewModel.EmailMessage =
                RegexPatterns.AddMessage(data.First().Email != viewModel.Email, "This email already register");

            return View(viewModel);
        }

        public IActionResult Login()
        {
            if (Request.Cookies["Id"] != null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(AccountLoginViewModel viewModel)
        {
            viewModel.EmailMessage = string.Empty;
            viewModel.PasswordMessage = string.Empty;


            string endpoint = "User/GetAll";

            var dataAboutAllUsers = await httpClient.GetFromJsonAsync<List<UserDto>>(endpoint);

            var data = dataAboutAllUsers.Where(u => u.Email == viewModel.Email).First();


            if (data == null)
            {
                viewModel.EmailMessage = "This email not register";

                return View(viewModel);
            }

            if (viewModel.Password == data.Password)
            {
                CookieOptions cookie = new CookieOptions();
                cookie.Expires = DateTime.Now.AddMinutes(60);

                Response.Cookies.Append("Id", data.Id, cookie);
                Response.Cookies.Append("UserName", $"{data.FirstName} {data.LastName}", cookie);
                Response.Cookies.Append("UserType", data.UserType, cookie);
                Response.Cookies.Append("Sex", data.Sex.ToString(), cookie);
                return RedirectToAction("Index", "Home");
            }

            viewModel.PasswordMessage = RegexPatterns.AddMessage(viewModel.Password == data.Password, "Wrong password");

            return View(viewModel);
        }


        public IActionResult Logout()
        {
            Response.Cookies.Delete("Id");
            Response.Cookies.Delete("UserName");
            Response.Cookies.Delete("UserType");
            Response.Cookies.Delete("Sex");
            return Redirect("/");
        }
    }
}

FoodHouse.UI/Views/Autentificate/Login.cshtml
@model FoodHouse.UI.Models.ViewModel.Account.AccountLoginViewModel;
@{
	char data = '@';
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>FoodHouse - Авторизація</title>
	<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>
<body>
	<header class="register-header reviews-header">
		<div class="logo-block">
			<a class="logo" asp-action="Index" asp-controller="Home">
				<i class="bx bx-store-alt logo-item"></i>
				<div class="logo-title">Food<span>House</span></div>
			</a>
		</div>
	</header>
	<main class="register-main">
		<div class="register-container">
			<div class="reg-img">
				<img src="~/images/img/log.png" style="max-height:700px" alt="img_1">
			</div>
			<form class="register-from" method="post">
				<h2 class="form-title">АВТОРИЗАЦІЯ</h2>
				@{
					if (!String.IsNullOrEmpty(Model != null ? Model.EmailMessage : string.Empty))
					{
						<input type="email" class="form-control" id="email" asp-for="Email" required placeholder="ivanovandrii@gmail.com">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.EmailMessage</p>
						</div>
					}
					else
					{
						<input type="email" class="form-control mb-2" id="email" asp-for="Email" required placeholder="ivanovandrii@gmail.com">
					}

					if (!String.IsNullOrEmpty(Model != null ? Model.PasswordMessage : string.Empty))
					{
						<input type="password" class="form-control" id="password" asp-for="Password" required placeholder="df9Df1uu">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.PasswordMessage</p>
						</div>
					}
					else
					{
						<input type="password" class="form-control mb-2" id="password" asp-for="Password" required placeholder="df9Df1uu">
					}
				}
				<div class="reg-link">
					<button class="btn-register" type="submit">Вхід</button>
					<div class="log-btn"><a asp-controller="Autentificate" asp-action="Register">Реєстрація</a></div>
				</div>
			</form>
		</div>
	</main>
	<footer class="footer">
		<div class="footer-wrapper">
			<div class="footer-first">
				<div class="footer-logo">
					<a class="f-logo" href="#">
						<!--                    <img src="~/images/icons/footer_logo.svg" class="logo-img" alt="logo_img">-->
						<i class="bx bx-store-alt f-item"></i>
						<div class="f-logo">FoodHouse</div>
					</a>
				</div>
				<div class="footer-menu">
					<a href="#">Меню</a>
				</div>
				<div class="footer-support">
					<a href="#">Тех. підтримка</a>
				</div>
				<div class="footer-login">
					<a asp-controller="Autentificate" asp-action="Login">Вхід в кабінет</a>
				</div>
			</div>
			<div class="footer-second">
				<h2 class="footer-social">СОЦІАЛЬНІ МЕРЕЖІ</h2>
				<div class="footer-mediablock">
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/instagram.png" alt="instagram">
							<div class="footer-instagram">@data FH_instagram</div>
						</a>
					</div>
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/facebook.png" alt="facebook">
							<div class="footer-instagram">@data FH_facebook</div>
						</a>
					</div>
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/twitter.png" alt="twitter">
							<div class="footer-instagram">@data FH_twitter</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
	<script>new Snowflakes();</script>
</body>
</html>

FoodHouse.UI/Views/Autentificate/Register.cshtml
@model FoodHouse.UI.Models.ViewModel.Account.AccountRegisterViewModel;
@{
	char data = '@';
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>FoodHouse - Реєстрація</title>
	<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>
<body>
	<header class="register-header reviews-header">
		<div class="logo-block">
			<a class="logo" asp-action="Index" asp-controller="Home">
				<i class="bx bx-store-alt logo-item"></i>
				<div class="logo-title">Food<span>House</span></div>
			</a>
		</div>
	</header>
	<main class="register-main">
		<div class="register-container">
			<div class="reg-img">
				<img src="~/images/img/reg.png" style="max-height:700px" alt="img_1">
			</div>
			<form class="register-from" method="post">
				@{
					<h2 class="form-title">ЗАРЕЄСТРУВАТИСЯ</h2>
					if (!String.IsNullOrEmpty(Model != null ? Model.FirstNameMessage : string.Empty))
					{
						<input type="text" class="form-control" id="fname" asp-for="FirstName" required placeholder="Andrii" maxlength="13">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.FirstNameMessage</p>
						</div>
					}
					else
					{
						<input type="text" class="form-control mb-2" id="fname" asp-for="FirstName" required placeholder="Andrii" maxlength="13">
					}

					if (!String.IsNullOrEmpty(Model != null ? Model.LastNameMessage : string.Empty))
					{
						<input type="text" class="form-control" id="lname" asp-for="LastName" required placeholder="Ivanov" maxlength="13">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.LastNameMessage</p>
						</div>
					}
					else
					{
						<input type="text" class="form-control mb-2" id="lname" asp-for="LastName" required placeholder="Ivanov" maxlength="13">
					}

					<select asp-for="Sex" class="form-control" name="sex">
						<option value="" disabled selected hidden>Стать</option>
						<option value="male">Жіноча</option>
						<option value="female">Чоловіча</option>
					</select>

					if (!String.IsNullOrEmpty(Model != null ? Model.EmailMessage : string.Empty))
					{
						<input type="email" class="form-control" id="email" asp-for="Email" required placeholder="ivanovandrii@gmail.com">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.EmailMessage</p>
						</div>
					}
					else
					{
						<input type="email" class="form-control mb-2" id="email" asp-for="Email" required placeholder="ivanovandrii@gmail.com">
					}

					if (!String.IsNullOrEmpty(Model != null ? Model.NumberMessage : string.Empty))
					{
						<input type="text" class="form-control" id="number" asp-for="Number" required placeholder="098 535-434" maxlength="15">

						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.NumberMessage</p>
						</div>
					}
					else
					{
						<input type="text" class="form-control mb-2" id="number" asp-for="Number" required placeholder="098 535-434" maxlength="15">
					}
					if (!String.IsNullOrEmpty(Model != null ? Model.PasswordMessage : string.Empty))
					{
						<input type="password" class="form-control" id="password" asp-for="Password" required placeholder="df9Df1uu">
						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.PasswordMessage</p>
						</div>
					}
					else
					{
						<input type="password" class="form-control mb-2" id="password" asp-for="Password" required placeholder="df9Df1uu">
					}

					if (!String.IsNullOrEmpty(Model != null ? Model.PasswordMessage : string.Empty))
					{
						<input type="password" class="form-control" id="confirmPassword" asp-for="PasswordConfirm" required placeholder="df9Df1uu">

						<div class="alert alert-dismissible alert-danger problem">
							<p style="font-size:12px; text-align:center" class="mt-3">@Model.PasswordMessage</p>
						</div>
					}
					else
					{
						<input type="password" class="form-control mb-2" id="confirmPassword" asp-for="PasswordConfirm" required placeholder="df9Df1uu">
					}
					<div class="reg-link">
						<button class="btn-register" type="submit">Реєстрація</button>
						<div class="log-btn"><a asp-controller="Autentificate" asp-action="Login">Вхід</a></div>
					</div>
				}
			</form>

		</div>
	</main>
	<footer class="footer">
		<div class="footer-wrapper">
			<div class="footer-first">
				<div class="footer-logo">
					<a class="f-logo" href="#">
						<!--                    <img src="~/images/icons/footer_logo.svg" class="logo-img" alt="logo_img">-->
						<i class="bx bx-store-alt f-item"></i>
						<div class="f-logo">FoodHouse</div>
					</a>
				</div>
				<div class="footer-menu">
					<a href="#">Меню</a>
				</div>
				<div class="footer-support">
					<a href="#">Тех. підтримка</a>
				</div>
				<div class="footer-login">
					<a asp-controller="Autentificate" asp-action="Login">Вхід в кабінет</a>
				</div>
			</div>
			<div class="footer-second">
				<h2 class="footer-social">СОЦІАЛЬНІ МЕРЕЖІ</h2>
				<div class="footer-mediablock">
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/instagram.png" alt="instagram">
							<div class="footer-instagram">@data FH_instagram</div>
						</a>
					</div>
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/facebook.png" alt="facebook">
							<div class="footer-instagram">@data FH_facebook</div>
						</a>
					</div>
					<div class="footer-media">
						<a href="#">
							<img src="~/images/icons/twitter.png" alt="twitter">
							<div class="footer-instagram">@data FH_twitter</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
	<script>new Snowflakes();</script>
</body>
</html>